<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="1" ignored="0" total="13" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="144569" started-at="2020-02-20T00:19:29Z" finished-at="2020-02-20T00:21:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="144569" started-at="2020-02-20T00:19:29Z" finished-at="2020-02-20T00:21:54Z">
      <class name="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="beforeTest" is-config="true" duration-ms="7871" started-at="2020-02-20T00:19:29Z" finished-at="2020-02-20T00:19:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="step01()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step01" duration-ms="18652" started-at="2020-02-20T00:19:37Z" finished-at="2020-02-20T00:19:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step01 -->
        <test-method status="PASS" signature="step02()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step02" duration-ms="8533" started-at="2020-02-20T00:19:56Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step01" finished-at="2020-02-20T00:20:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step02 -->
        <test-method status="PASS" signature="step03()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step03" duration-ms="19783" started-at="2020-02-20T00:20:04Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step02" finished-at="2020-02-20T00:20:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step03 -->
        <test-method status="PASS" signature="step04()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step04" duration-ms="19937" started-at="2020-02-20T00:20:24Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step03" finished-at="2020-02-20T00:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step04 -->
        <test-method status="PASS" signature="step05()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step05" duration-ms="7357" started-at="2020-02-20T00:20:44Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step04" finished-at="2020-02-20T00:20:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step05 -->
        <test-method status="PASS" signature="step06()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step06" duration-ms="5276" started-at="2020-02-20T00:20:52Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step05" finished-at="2020-02-20T00:20:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step06 -->
        <test-method status="PASS" signature="step07()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step07" duration-ms="24526" started-at="2020-02-20T00:20:57Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step06" finished-at="2020-02-20T00:21:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step07 -->
        <test-method status="FAIL" signature="step08()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step08" duration-ms="27367" started-at="2020-02-20T00:21:21Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step07" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Test Failed on Step 8]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Test Failed on Step 8
at delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step08(SOI_76_TC1_MobileOrderIntake_CaseCreation.java:372)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Closing Won Opportunity - Failed
at actions.FunctionalActionsSFDS.closeWonOppie(FunctionalActionsSFDS.java:208)
at delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step08(SOI_76_TC1_MobileOrderIntake_CaseCreation.java:349)
... 25 more
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"flexipage\-aura\-wrapper"}
  (Session info: chrome=80.0.3987.116)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INNOWAVE-383', ip: '192.168.0.164', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_212'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.116, chrome: {chromedriverVersion: 80.0.3987.16 (320f6526c1632..., userDataDir: C:\Users\luis.achas\AppData...}, goog:chromeOptions: {debuggerAddress: localhost:61775}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 9e3068a0474848aad6b59f2147cdc6ec
*** Element info: {Using=tag name, value=flexipage-aura-wrapper}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByTagName(RemoteWebDriver.java:396)
at org.openqa.selenium.By$ByTagName.findElement(By.java:320)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at actions.FunctionalActionsSFDS.closeWonOppie(FunctionalActionsSFDS.java:183)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step08 -->
        <test-method status="SKIP" signature="step09()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step09" duration-ms="0" started-at="2020-02-20T00:21:49Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step08" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step09()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step09()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step09 -->
        <test-method status="SKIP" signature="step10()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step10" duration-ms="0" started-at="2020-02-20T00:21:49Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step09" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step10()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step10()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step10 -->
        <test-method status="SKIP" signature="step11()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step11" duration-ms="0" started-at="2020-02-20T00:21:49Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step10" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step11()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step11()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step11 -->
        <test-method status="SKIP" signature="step12()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step12" duration-ms="0" started-at="2020-02-20T00:21:49Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step11" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step12()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step12()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step12 -->
        <test-method status="SKIP" signature="step13()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="step13" duration-ms="0" started-at="2020-02-20T00:21:49Z" depends-on-methods="delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation.step12" finished-at="2020-02-20T00:21:49Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step13()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SOI_76_TC1_MobileOrderIntake_CaseCreation.step13()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- step13 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation@6eebc39e]" name="afterTest" is-config="true" duration-ms="5110" started-at="2020-02-20T00:21:49Z" finished-at="2020-02-20T00:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- delivery01.soi_76.SOI_76_TC1_MobileOrderIntake_CaseCreation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
